/** Catalogue of mock VS Code extensions for the workSphere Coding workspace.
 *  Categories: ai, formatter, linter, language, theme, icons, git, remote,
 *  productivity, snippets, debug, markdown, web, other.
 */

export const EXTENSION_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'installed', label: 'Installed' },
  { id: 'popular', label: 'Popular' },
  { id: 'recommended', label: 'Recommended' },
  { id: 'ai', label: 'AI' },
  { id: 'language', label: 'Languages' },
  { id: 'formatter', label: 'Formatters' },
  { id: 'linter', label: 'Linters' },
  { id: 'theme', label: 'Themes' },
  { id: 'icons', label: 'Icons' },
  { id: 'git', label: 'Git' },
  { id: 'remote', label: 'Remote' },
  { id: 'productivity', label: 'Productivity' },
  { id: 'snippets', label: 'Snippets' },
  { id: 'debug', label: 'Debug' },
  { id: 'markdown', label: 'Markdown' },
  { id: 'web', label: 'Web' },
]

export const EXTENSIONS = [
  // ----- AI / Copilots -----
  {
    id: 'github.copilot',
    name: 'GitHub Copilot',
    publisher: 'GitHub',
    verified: true,
    downloads: 32_800_000,
    rating: 4.5,
    category: 'ai',
    popular: true,
    recommended: true,
    desc: 'Your AI pair programmer — code suggestions powered by OpenAI.',
    short: 'CP',
  },
  {
    id: 'github.copilot-chat',
    name: 'GitHub Copilot Chat',
    publisher: 'GitHub',
    verified: true,
    downloads: 18_400_000,
    rating: 4.4,
    category: 'ai',
    popular: true,
    desc: 'AI chat features powered by Copilot — explain, fix, generate tests.',
    short: 'CC',
  },
  {
    id: 'tabnine.tabnine-vscode',
    name: 'Tabnine: AI Autocomplete & Chat',
    publisher: 'Tabnine',
    verified: true,
    downloads: 11_900_000,
    rating: 4.4,
    category: 'ai',
    popular: true,
    desc: 'AI assistant for software developers — autocomplete, refactor, test.',
    short: 'TN',
  },
  {
    id: 'continue.continue',
    name: 'Continue',
    publisher: 'Continue',
    downloads: 1_900_000,
    rating: 4.6,
    category: 'ai',
    desc: 'The open-source AI code assistant. Use any model.',
    short: 'C',
  },
  {
    id: 'codeium.codeium',
    name: 'Codeium: AI Coding Autocomplete',
    publisher: 'Codeium',
    downloads: 4_200_000,
    rating: 4.7,
    category: 'ai',
    popular: true,
    desc: 'Free AI code completion and chat in 70+ languages.',
    short: 'CO',
  },

  // ----- Formatters / Linters -----
  {
    id: 'esbenp.prettier-vscode',
    name: 'Prettier - Code formatter',
    publisher: 'Prettier',
    verified: true,
    downloads: 45_200_000,
    rating: 4.4,
    category: 'formatter',
    popular: true,
    recommended: true,
    installed: true,
    desc: 'Opinionated code formatter for JS, TS, CSS, HTML, JSON, Markdown.',
    short: 'PR',
  },
  {
    id: 'dbaeumer.vscode-eslint',
    name: 'ESLint',
    publisher: 'Microsoft',
    verified: true,
    downloads: 38_400_000,
    rating: 4.5,
    category: 'linter',
    popular: true,
    recommended: true,
    installed: true,
    desc: 'Integrates ESLint JavaScript into VS Code.',
    short: 'ES',
  },
  {
    id: 'editorconfig.editorconfig',
    name: 'EditorConfig for VS Code',
    publisher: 'EditorConfig',
    verified: true,
    downloads: 9_200_000,
    rating: 4.5,
    category: 'formatter',
    desc: 'EditorConfig support for Visual Studio Code.',
    short: 'EC',
  },
  {
    id: 'streetsidesoftware.code-spell-checker',
    name: 'Code Spell Checker',
    publisher: 'Street Side Software',
    downloads: 8_400_000,
    rating: 4.7,
    category: 'linter',
    desc: 'Spelling checker for source code.',
    short: 'CS',
  },
  {
    id: 'sonarsource.sonarlint-vscode',
    name: 'SonarLint',
    publisher: 'SonarSource',
    verified: true,
    downloads: 5_700_000,
    rating: 4.4,
    category: 'linter',
    desc: 'Detect bugs, vulnerabilities and code smells while you code.',
    short: 'SL',
  },

  // ----- Languages -----
  {
    id: 'ms-python.python',
    name: 'Python',
    publisher: 'Microsoft',
    verified: true,
    downloads: 142_000_000,
    rating: 4.4,
    category: 'language',
    popular: true,
    recommended: true,
    installed: true,
    desc: 'IntelliSense (Pylance), linting, debugging, code navigation for Python.',
    short: 'Py',
  },
  {
    id: 'ms-python.vscode-pylance',
    name: 'Pylance',
    publisher: 'Microsoft',
    verified: true,
    downloads: 105_000_000,
    rating: 4.5,
    category: 'language',
    popular: true,
    desc: 'Fast, feature-rich language support for Python.',
    short: 'PL',
  },
  {
    id: 'ms-toolsai.jupyter',
    name: 'Jupyter',
    publisher: 'Microsoft',
    verified: true,
    downloads: 78_000_000,
    rating: 4.3,
    category: 'language',
    popular: true,
    desc: 'Jupyter notebook support, interactive programming and computing.',
    short: 'Jp',
  },
  {
    id: 'ms-vscode.cpptools',
    name: 'C/C++',
    publisher: 'Microsoft',
    verified: true,
    downloads: 82_300_000,
    rating: 4.0,
    category: 'language',
    popular: true,
    desc: 'C/C++ IntelliSense, debugging, and code browsing.',
    short: 'C++',
  },
  {
    id: 'ms-dotnettools.csharp',
    name: 'C#',
    publisher: 'Microsoft',
    verified: true,
    downloads: 38_600_000,
    rating: 4.0,
    category: 'language',
    desc: 'Base language support for C# from the C# Dev Kit.',
    short: 'C#',
  },
  {
    id: 'redhat.java',
    name: 'Extension Pack for Java',
    publisher: 'Microsoft',
    verified: true,
    downloads: 18_200_000,
    rating: 4.2,
    category: 'language',
    desc: 'Java extension pack for VS Code — language support, debugger, Maven.',
    short: 'Jv',
  },
  {
    id: 'golang.go',
    name: 'Go',
    publisher: 'Go Team at Google',
    verified: true,
    downloads: 11_700_000,
    rating: 4.5,
    category: 'language',
    desc: 'Rich Go language support for Visual Studio Code.',
    short: 'Go',
  },
  {
    id: 'rust-lang.rust-analyzer',
    name: 'rust-analyzer',
    publisher: 'The Rust Programming Language',
    verified: true,
    downloads: 7_900_000,
    rating: 4.6,
    category: 'language',
    desc: 'Rust language support — IntelliSense and debugging.',
    short: 'Rs',
  },
  {
    id: 'vue.volar',
    name: 'Vue - Official',
    publisher: 'Vue',
    verified: true,
    downloads: 9_400_000,
    rating: 4.5,
    category: 'language',
    desc: 'Language support for Vue 3 (Volar) — official.',
    short: 'Vu',
  },
  {
    id: 'svelte.svelte-vscode',
    name: 'Svelte for VS Code',
    publisher: 'Svelte',
    verified: true,
    downloads: 3_800_000,
    rating: 4.5,
    category: 'language',
    desc: 'Svelte language support for VS Code.',
    short: 'Sv',
  },
  {
    id: 'angular.ng-template',
    name: 'Angular Language Service',
    publisher: 'Angular',
    verified: true,
    downloads: 5_200_000,
    rating: 4.4,
    category: 'language',
    desc: 'Editor services for Angular templates.',
    short: 'Ng',
  },
  {
    id: 'bmewburn.vscode-intelephense-client',
    name: 'PHP Intelephense',
    publisher: 'Ben Mewburn',
    downloads: 12_400_000,
    rating: 4.7,
    category: 'language',
    desc: 'High-performance PHP language server.',
    short: 'PH',
  },
  {
    id: 'redhat.vscode-yaml',
    name: 'YAML',
    publisher: 'Red Hat',
    verified: true,
    downloads: 22_400_000,
    rating: 4.4,
    category: 'language',
    desc: 'YAML Language Support by Red Hat with built-in Kubernetes syntax support.',
    short: 'Yl',
  },
  {
    id: 'redhat.vscode-xml',
    name: 'XML',
    publisher: 'Red Hat',
    verified: true,
    downloads: 11_800_000,
    rating: 4.6,
    category: 'language',
    desc: 'XML Language Support by Red Hat.',
    short: 'Xm',
  },
  {
    id: 'bradlc.vscode-tailwindcss',
    name: 'Tailwind CSS IntelliSense',
    publisher: 'Tailwind Labs',
    verified: true,
    downloads: 12_900_000,
    rating: 4.7,
    category: 'web',
    popular: true,
    desc: 'Intelligent Tailwind CSS tooling for VS Code.',
    short: 'Tw',
  },

  // ----- Themes / Icons -----
  {
    id: 'pkief.material-icon-theme',
    name: 'Material Icon Theme',
    publisher: 'Philipp Kief',
    downloads: 28_400_000,
    rating: 4.9,
    category: 'icons',
    popular: true,
    desc: 'Material Design Icons for Visual Studio Code.',
    short: 'Mi',
  },
  {
    id: 'vscode-icons-team.vscode-icons',
    name: 'vscode-icons',
    publisher: 'VSCode Icons Team',
    downloads: 21_600_000,
    rating: 4.6,
    category: 'icons',
    desc: 'Icons for Visual Studio Code.',
    short: 'vI',
  },
  {
    id: 'zhuangtongfa.material-theme',
    name: 'One Dark Pro',
    publisher: 'binaryify',
    downloads: 12_200_000,
    rating: 4.6,
    category: 'theme',
    popular: true,
    desc: 'Atom\u2019s iconic One Dark theme for Visual Studio Code.',
    short: '1D',
  },
  {
    id: 'dracula-theme.theme-dracula',
    name: 'Dracula Official',
    publisher: 'Dracula Theme',
    verified: true,
    downloads: 8_800_000,
    rating: 4.8,
    category: 'theme',
    desc: 'Official Dracula theme. A dark theme for many editors.',
    short: 'Dr',
  },
  {
    id: 'sdras.night-owl',
    name: 'Night Owl',
    publisher: 'Sarah Drasner',
    downloads: 3_900_000,
    rating: 4.7,
    category: 'theme',
    desc: 'A VS Code theme for the night owls out there.',
    short: 'No',
  },
  {
    id: 'akamud.vscode-theme-onedark',
    name: 'Atom One Dark Theme',
    publisher: 'Akamud',
    downloads: 4_200_000,
    rating: 4.7,
    category: 'theme',
    desc: 'Atom One Dark theme for Visual Studio Code.',
    short: 'AO',
  },
  {
    id: 'github.github-vscode-theme',
    name: 'GitHub Theme',
    publisher: 'GitHub',
    verified: true,
    downloads: 6_100_000,
    rating: 4.5,
    category: 'theme',
    desc: 'GitHub theme for VS Code — light and dark variants.',
    short: 'Gh',
  },

  // ----- Git -----
  {
    id: 'eamodio.gitlens',
    name: 'GitLens — Git supercharged',
    publisher: 'GitKraken',
    verified: true,
    downloads: 33_800_000,
    rating: 4.7,
    category: 'git',
    popular: true,
    recommended: true,
    desc: 'Supercharge Git within VS Code — visualize code authorship at a glance.',
    short: 'GL',
  },
  {
    id: 'github.vscode-pull-request-github',
    name: 'GitHub Pull Requests',
    publisher: 'GitHub',
    verified: true,
    downloads: 9_800_000,
    rating: 4.3,
    category: 'git',
    desc: 'Review and manage your GitHub pull requests and issues directly in VS Code.',
    short: 'PR',
  },
  {
    id: 'mhutchie.git-graph',
    name: 'Git Graph',
    publisher: 'mhutchie',
    downloads: 6_200_000,
    rating: 4.9,
    category: 'git',
    desc: 'View a Git Graph of your repository.',
    short: 'Gg',
  },
  {
    id: 'donjayamanne.githistory',
    name: 'Git History',
    publisher: 'Don Jayamanne',
    downloads: 5_400_000,
    rating: 4.5,
    category: 'git',
    desc: 'View git log, file history, compare branches or commits.',
    short: 'Gh',
  },

  // ----- Remote development -----
  {
    id: 'ms-vscode-remote.remote-ssh',
    name: 'Remote - SSH',
    publisher: 'Microsoft',
    verified: true,
    downloads: 28_000_000,
    rating: 4.4,
    category: 'remote',
    popular: true,
    desc: 'Open any folder on a remote machine using SSH.',
    short: 'SS',
  },
  {
    id: 'ms-vscode-remote.remote-containers',
    name: 'Dev Containers',
    publisher: 'Microsoft',
    verified: true,
    downloads: 22_400_000,
    rating: 4.4,
    category: 'remote',
    popular: true,
    desc: 'Open any folder or repository inside a Docker container.',
    short: 'Dc',
  },
  {
    id: 'ms-vscode-remote.remote-wsl',
    name: 'WSL',
    publisher: 'Microsoft',
    verified: true,
    downloads: 21_700_000,
    rating: 4.4,
    category: 'remote',
    desc: 'Open any folder in the Windows Subsystem for Linux.',
    short: 'WS',
  },
  {
    id: 'ms-vsliveshare.vsliveshare',
    name: 'Live Share',
    publisher: 'Microsoft',
    verified: true,
    downloads: 16_800_000,
    rating: 4.0,
    category: 'remote',
    desc: 'Real-time collaborative development from the comfort of your favorite tools.',
    short: 'LS',
  },

  // ----- Productivity -----
  {
    id: 'ritwickdey.liveserver',
    name: 'Live Server',
    publisher: 'Ritwick Dey',
    downloads: 52_300_000,
    rating: 4.6,
    category: 'productivity',
    popular: true,
    recommended: true,
    installed: true,
    desc: 'Launch a development local Server with live reload for static & dynamic pages.',
    short: 'LV',
  },
  {
    id: 'formulahendry.code-runner',
    name: 'Code Runner',
    publisher: 'Jun Han',
    downloads: 28_100_000,
    rating: 4.5,
    category: 'productivity',
    popular: true,
    desc: 'Run code snippet or code file for multiple languages.',
    short: 'CR',
  },
  {
    id: 'formulahendry.auto-rename-tag',
    name: 'Auto Rename Tag',
    publisher: 'Jun Han',
    downloads: 22_400_000,
    rating: 4.5,
    category: 'productivity',
    desc: 'Auto rename paired HTML/XML tag.',
    short: 'AR',
  },
  {
    id: 'formulahendry.auto-close-tag',
    name: 'Auto Close Tag',
    publisher: 'Jun Han',
    downloads: 12_600_000,
    rating: 4.6,
    category: 'productivity',
    desc: 'Automatically add HTML/XML close tag.',
    short: 'AC',
  },
  {
    id: 'christian-kohler.path-intellisense',
    name: 'Path Intellisense',
    publisher: 'Christian Kohler',
    downloads: 14_200_000,
    rating: 4.4,
    category: 'productivity',
    desc: 'Visual Studio Code plugin that autocompletes filenames.',
    short: 'Pi',
  },
  {
    id: 'usernamehw.errorlens',
    name: 'Error Lens',
    publisher: 'Alexander',
    downloads: 9_800_000,
    rating: 4.9,
    category: 'productivity',
    popular: true,
    desc: 'Improve highlighting of errors, warnings and other language diagnostics.',
    short: 'EL',
  },
  {
    id: 'gruntfuggly.todo-tree',
    name: 'Todo Tree',
    publisher: 'Gruntfuggly',
    downloads: 6_700_000,
    rating: 4.7,
    category: 'productivity',
    desc: 'Show TODO, FIXME, etc. comment tags in a tree view.',
    short: 'TT',
  },
  {
    id: 'aaron-bond.better-comments',
    name: 'Better Comments',
    publisher: 'Aaron Bond',
    downloads: 7_400_000,
    rating: 4.7,
    category: 'productivity',
    desc: 'Improve your code commenting by annotating with alert, info, todo, and more.',
    short: 'Bc',
  },
  {
    id: 'wix.vscode-import-cost',
    name: 'Import Cost',
    publisher: 'Wix',
    downloads: 4_900_000,
    rating: 4.4,
    category: 'productivity',
    desc: 'Display import/require package size in the editor.',
    short: 'Ic',
  },
  {
    id: 'wallabyjs.quokka-vscode',
    name: 'Quokka.js',
    publisher: 'Wallaby.js',
    downloads: 2_400_000,
    rating: 4.6,
    category: 'productivity',
    desc: 'JavaScript and TypeScript playground in your editor.',
    short: 'Qu',
  },
  {
    id: 'visualstudioexptteam.vscodeintellicode',
    name: 'IntelliCode',
    publisher: 'Microsoft',
    verified: true,
    downloads: 38_900_000,
    rating: 4.1,
    category: 'ai',
    popular: true,
    desc: 'AI-assisted IntelliSense by learning from your code.',
    short: 'IC',
  },
  {
    id: 'wakatime.vscode-wakatime',
    name: 'WakaTime',
    publisher: 'WakaTime',
    downloads: 3_800_000,
    rating: 4.6,
    category: 'productivity',
    desc: 'Metrics, insights and time tracking automatically generated from your activity.',
    short: 'Wk',
  },

  // ----- Snippets -----
  {
    id: 'dsznajder.es7-react-js-snippets',
    name: 'ES7+ React/Redux/React-Native snippets',
    publisher: 'dsznajder',
    downloads: 12_900_000,
    rating: 4.6,
    category: 'snippets',
    popular: true,
    desc: 'Simple extensions for React, Redux and Graphql in JS/TS.',
    short: 'R7',
  },
  {
    id: 'xabikos.javascriptsnippets',
    name: 'JavaScript (ES6) code snippets',
    publisher: 'Charalampos Karypidis',
    downloads: 8_400_000,
    rating: 4.4,
    category: 'snippets',
    desc: 'Code snippets for JavaScript in ES6 syntax.',
    short: 'Js',
  },

  // ----- Web / API -----
  {
    id: 'rangav.vscode-thunder-client',
    name: 'Thunder Client',
    publisher: 'Ranga Vadhineni',
    downloads: 4_900_000,
    rating: 4.6,
    category: 'web',
    desc: 'Lightweight Rest API Client for VS Code.',
    short: 'Th',
  },
  {
    id: 'humao.rest-client',
    name: 'REST Client',
    publisher: 'Huachao Mao',
    downloads: 6_200_000,
    rating: 4.7,
    category: 'web',
    desc: 'REST Client for Visual Studio Code.',
    short: 'Rc',
  },
  {
    id: 'ms-azuretools.vscode-docker',
    name: 'Docker',
    publisher: 'Microsoft',
    verified: true,
    downloads: 39_400_000,
    rating: 4.4,
    category: 'web',
    popular: true,
    desc: 'Makes it easy to create, manage, and debug containerized applications.',
    short: 'Dk',
  },

  // ----- Markdown -----
  {
    id: 'yzhang.markdown-all-in-one',
    name: 'Markdown All in One',
    publisher: 'Yu Zhang',
    downloads: 14_700_000,
    rating: 4.7,
    category: 'markdown',
    popular: true,
    desc: 'All you need to write Markdown (keyboard shortcuts, TOC, auto preview).',
    short: 'Md',
  },
  {
    id: 'shd101wyy.markdown-preview-enhanced',
    name: 'Markdown Preview Enhanced',
    publisher: 'Yiyi Wang',
    downloads: 8_900_000,
    rating: 4.5,
    category: 'markdown',
    desc: 'Markdown Preview Enhanced for VS Code (math, diagrams, exports).',
    short: 'Me',
  },
  {
    id: 'davidanson.vscode-markdownlint',
    name: 'markdownlint',
    publisher: 'David Anson',
    downloads: 7_200_000,
    rating: 4.6,
    category: 'markdown',
    desc: 'Markdown linting and style checking for Visual Studio Code.',
    short: 'Ml',
  },

  // ----- Debug / Misc -----
  {
    id: 'msjsdiag.debugger-for-chrome',
    name: 'Debugger for Chrome',
    publisher: 'Microsoft',
    verified: true,
    downloads: 13_600_000,
    rating: 4.2,
    category: 'debug',
    desc: 'Debug your JavaScript code in the Google Chrome browser.',
    short: 'Dc',
  },
  {
    id: 'naumovs.color-highlight',
    name: 'Color Highlight',
    publisher: 'Sergii Naumov',
    downloads: 5_900_000,
    rating: 4.7,
    category: 'web',
    desc: 'Highlight web colors in your editor.',
    short: 'Ch',
  },
  {
    id: 'pranaygp.vscode-css-peek',
    name: 'CSS Peek',
    publisher: 'Pranay Prakash',
    downloads: 6_800_000,
    rating: 4.5,
    category: 'web',
    desc: 'Allow peeking to CSS ID and class definitions.',
    short: 'CP',
  },
  {
    id: 'oderwat.indent-rainbow',
    name: 'indent-rainbow',
    publisher: 'oderwat',
    downloads: 7_200_000,
    rating: 4.7,
    category: 'productivity',
    desc: 'Makes indentation easier to read.',
    short: 'Ir',
  },
]

const CATEGORY_GRADIENTS = {
  ai: 'linear-gradient(135deg,#06b6d4,#0e7490)',
  formatter: 'linear-gradient(135deg,#f97316,#c2410c)',
  linter: 'linear-gradient(135deg,#eab308,#a16207)',
  language: 'linear-gradient(135deg,#2563eb,#1e40af)',
  theme: 'linear-gradient(135deg,#a855f7,#6b21a8)',
  icons: 'linear-gradient(135deg,#ec4899,#9d174d)',
  git: 'linear-gradient(135deg,#f43f5e,#9f1239)',
  remote: 'linear-gradient(135deg,#10b981,#065f46)',
  productivity: 'linear-gradient(135deg,#0ea5e9,#0c4a6e)',
  snippets: 'linear-gradient(135deg,#22c55e,#15803d)',
  debug: 'linear-gradient(135deg,#f59e0b,#92400e)',
  markdown: 'linear-gradient(135deg,#64748b,#1e293b)',
  web: 'linear-gradient(135deg,#14b8a6,#0f766e)',
}

export function extensionColor(category) {
  return CATEGORY_GRADIENTS[category] || 'linear-gradient(135deg,#475569,#1e293b)'
}

export function formatDownloads(n) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1)}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`
  return String(n)
}
